name: Hyoflix
title: Hyoflix | A blog theme for Jekyll
description: Hyolix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: shinhyojeong119@gmail.com
disqus_username: disqus_username
